### ISSUE TITLE
build a distributed bundle

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-accessibility#17]
similar to the other gl-js plugins, we could build a dist bundle which dev's can include in a script tag

I'm working on a PR for this, but getting stuck as it's giving me SyntaxErrors around:

   clearMarkers = () => {

Not sure what ES level that syntax is...

**Comment by tristen** [comment]
Arrow functions were [introduced in ES6](https://hacks.mozilla.org/2015/06/es6-in-depth-arrow-functions/)!

**Comment by andrewharvey** [comment]
Thanks, With that in mind, I'll try a bit more to see if I can get it transpiling into a distributable build.

**Comment by marharyta** [comment]
@andrewharvey what is the situation with that? I am currently building an app that might critically need good a11y (city project) and I want to know if there is any CDN I can use? Thanks a lot for your work! Also, do you need help? I am not good with maps but I can try!

**Comment by andrewharvey** [comment]
@marharyta I'm not working on this at the moment, so feel free to give it a go yourself. You can take a look at a similar project https://github.com/mapbox/mapbox-gl-draw/blob/master/package.json and see how it generates the dist build and try to replicate that here?

**Comment by allthesignals** [comment]
@marharyta I also am working on a few city projects, getting the same issue here.

I'll take a look and see if we can get it building!

**Comment by allthesignals** [comment]
I am also running into this syntax error. Babel doesn't seem to be seeing this plugin: https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html

When I change the syntax from the arrow function style syntax to class method syntax (`myProp = () => { }` to `myProp(){ }`), I'm able to build; Babel can transform without issue. 

~There is a [slight difference](https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1), but not relevant here. That said, I will keep trying to see why arrow function methods aren't working (I'd rather understand why this wasn't working in the first place than work around).~ Oops, it is relevant. These are event callbacks :) so binding matters.

Fork here until I get something ready for PR: https://github.com/allthesignals/mapbox-gl-accessibility

**Comment by allthesignals** [comment]
What are some next steps for this? I want to help but I'm not sure what needs to happen to publish this onto npm and a CDN? I'm assuming this will need to happen on Mapbox's account...

**Comment by tristen** [comment]
👋 @allthesignals I can help with the publish step to npm. OK to do that when https://github.com/mapbox/mapbox-gl-accessibility/pull/34 is merged?

**Comment by allthesignals** [comment]
@tristen you bet! as soon as that's merged i'll PR a simple test suite so we can refactor stuff.
