### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-accessibility#23]
The demo link https://www.mapbox.com/mapbox-gl-accessibility/ is 404. I'm not sure what it should be though.

**Comment by andrewharvey** [comment]
I think it was just the demo you get from `npm start`

**Comment by andrewharvey** [comment]
I think the best way forward here is to add an official example to the Mapbox GL JS examples, and point there instead.

**Comment by andrewharvey** [comment]
The readme now points to https://labs.mapbox.com/mapbox-gl-accessibility.
